no_trainings: 20
io_var:
  save_dir: ./Results/
  save_folder_name: pacs
  save_subfolder_name: thinpix2pix_hed
  train_dataset_list: 
    - ./Data/PACS/original_classes_photo_train.csv
  val_dataset_list:
    - ./Data/PACS/original_classes_photo_val.csv
  test_dataset_list: 
    - name: PACS
      directory:
        - ./Data/PACS/original_classes_sketch.csv
  load_model: None #a valid option is None
  nms_model: ./Pretrained_Models/opencv_extra.yml.gz
train:
  gpu: 0
  workers: 6
  batch: 64
  learning_rate: 0.0001
  weight_decay: 0
  epochs: 30
  schedule: 35
  architecture: resnet18
  pretrained: True
  optimizer: Adam #only Adam is currently supported
  criterion: cross_entropy #only cross entropy is currently supported
  sequence:
    - name: image2image
      path: ./Pretrained_Models/pix2pix_rand2outline_hed_initkaiminggain0.02_ep20_l10_0/epochs/generator_X_best_model.pth
      frozen: true
      use_grayscale: false
      architecture: official_resnet_generator
      input_nc: 1
      n_blocks: 9
      no_antialias: true
      no_antialias_up: true
      norm_layer: instance
      output_nc: 1
      use_dropout: false
extra_options:
  lr_mode: True
  nearest_neighbors: False #currently not supported
train_transforms:
  - name: random_resized_crop
    size: [224, 224]
    scale: [0.8, 1.0]
    ratio: [0.75, 1.3333333333333333]
  - name: random_horizontal_flip
    p: 0.5
  - name: edge_detector
    edge_mode: hed
val_transforms:
  - name: resize
    size: 224
  - name: edge_detector
    edge_mode: hed
test_transforms:
  - name: single
    transform:
      - name: black_background
      - name: square_np
      - name: resize_np
        size: 224
  - name: multi
    transform:
      - name: multi_scale
        size: 224
        size_multipliers: [0.9, 0.65, 0.45]
        return_white_bg: False
